
// AUTH
export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAIL = "auth/LOGIN_FAIL";
export const RESET_LOGIN_STATE = "auth/RESET_LOGIN_STATE";

export const SIGNUP = 'auth/SIGNUP';
export const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'auth/SIGNUP_FAIL';

export const LOGOUT = 'auth/LOGOUT';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'auth/LOGOUT_FAIL';

// HEADER
export const SEARCH_REQUEST = 'header/SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'header/SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAIL = 'header/SEARCH_REQUEST_FAIL';

export const NOTIFICATION_REQUEST = 'header/NOTIFICATION_REQUEST';
export const NOTIFICATION_REQUEST_SUCCESS = 'header/NOTIFICATION_REQUEST_SUCCESS';
export const NOTIFICATION_REQUEST_FAIL = 'header/NOTIFICATION_REQUEST_FAIL';

export const ACTIVE_USER_REQUEST = 'header/ACTIVE_USER_REQUEST';
export const ACTIVE_USER_REQUEST_SUCCESS = 'header/ACTIVE_USER_REQUEST_SUCCESS';
export const ACTIVE_USER_REQUEST_FAIL = 'header/ACTIVE_USER_REQUEST_FAIL';







