
// AUTH
export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAIL = "auth/LOGIN_FAIL";
export const RESET_LOGIN_STATE = "auth/RESET_LOGIN_STATE";

export const SIGNUP = 'auth/SIGNUP';
export const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'auth/SIGNUP_FAIL';

export const LOGOUT = 'auth/LOGOUT';
export const LOGOUT_SUCCESS = 'auth/LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'auth/LOGOUT_FAIL';

// HEADER
export const SEARCH_REQUEST = 'header/SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'header/SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAIL = 'header/SEARCH_REQUEST_FAIL';

export const NOTIFICATION_REQUEST = 'header/NOTIFICATION_REQUEST';
export const NOTIFICATION_REQUEST_SUCCESS = 'header/NOTIFICATION_REQUEST_SUCCESS';
export const NOTIFICATION_REQUEST_FAIL = 'header/NOTIFICATION_REQUEST_FAIL';

export const ACTIVE_USER_REQUEST = 'header/ACTIVE_USER_REQUEST';
export const ACTIVE_USER_REQUEST_SUCCESS = 'header/ACTIVE_USER_REQUEST_SUCCESS';
export const ACTIVE_USER_REQUEST_FAIL = 'header/ACTIVE_USER_REQUEST_FAIL';

// TOP NAV
export const LANGUAGE_OPTIONS_REQUEST = 'top-nav/LANGUAGE_OPTIONS_REQUEST';
export const LANGUAGE_OPTIONS_REQUEST_SUCCESS = 'top-nav/LANGUAGE_OPTIONS_REQUEST_SUCCESS';
export const LANGUAGE_OPTIONS_REQUEST_FAIL = 'top-nav/LANGUAGE_OPTIONS_REQUEST_FAIL';

export const TOP_MENU_REQUEST = 'top-nav/TOP_MENU_REQUEST';
export const TOP_MENU_REQUEST_SUCCESS = 'top-nav/TOP_MENU_REQUEST_SUCCESS';
export const TOP_MENU_REQUEST_FAIL = 'top-nav/TOP_MENU_REQUEST_FAIL';

// ASIDE
export const ASIDE_MENU_ITEM_REQUEST = 'aside/ASIDE_MENU_ITEM_REQUEST';
export const ASIDE_MENU_ITEM_REQUEST_SUCCESS = 'aside/ASIDE_MENU_ITEM_REQUEST_SUCCESS';
export const ASIDE_MENU_ITEM_REQUEST_FAIL = 'aside/ASIDE_MENU_ITEM_REQUEST_FAIL';

export const CLIENT_DETAILS_REQUEST = 'aside/CLIENT_DETAILS_REQUEST';
export const ASIDE_MENU_ITEM_REQUEST_SUCCESS = 'aside/ASIDE_MENU_ITEM_REQUEST_SUCCESS';
export const CLIENT_DETAILS_REQUEST_FAIL = 'aside/CLIENT_DETAILS_REQUEST_FAIL';

// DASHBOARD AREA 
export const CLIENT_DETAILS_REQUEST = 'dashboard-area/CHART_DATA_REQUEST';
export const ASIDE_MENU_ITEM_REQUEST_SUCCESS = 'dashboard-area/CHART_DATA_REQUEST_SUCCESS';
export const CLIENT_DETAILS_REQUEST_FAIL = 'dashboard-area/CHART_DATA_REQUEST_FAIL';

export const STAT_CARD_DATA_REQUEST = 'dashboard-area/STAT_CARD_DATA_REQUEST';
export const STAT_CARD_DATA_REQUEST_SUCCESS = 'dashboard-area/STAT_CARD_DATA_REQUEST_SUCCESS';
export const STAT_CARD_DATA_REQUEST_FAIL = 'dashboard-area/STAT_CARD_DATA_REQUEST_FAIL';

export const STAT_FILTER_ITEMS_REQUEST = 'dashboard-area/STAT_FILTER_ITEMS_REQUEST';
export const STAT_FILTER_ITEMS_REQUEST_SUCCESS = 'dashboard-area/STAT_FILTER_ITEMS_REQUEST_SUCCESS';
export const STAT_FILTER_ITEMS_REQUEST_FAIL = 'dashboard-area/STAT_FILTER_ITEMS_REQUEST_FAIL';

export const STAT_INFO_REQUEST = 'dashboard-area/STAT_INFO_REQUEST';
export const STAT_INFO_REQUEST_SUCCESS = 'dashboard-area/STAT_INFO_REQUEST_SUCCESS';
export const STAT_INFO_REQUEST_FAIL = 'dashboard-area/STAT_INFO_REQUEST_FAIL';

// FOOTER
export const SUBSCRIBE_REQUEST = 'footer/SUBSCRIBE_REQUEST';
export const SUBSCRIBE_REQUEST_SUCCESS = 'footer/SUBSCRIBE_REQUEST_SUCCESS';
export const SUBSCRIBE_REQUEST_FAIL = 'footer/SUBSCRIBE_REQUEST_FAIL';









