
export const LOGIN_REQUEST = "auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "auth/LOGIN_SUCCESS";
export const LOGIN_FAIL = "auth/LOGIN_FAIL";
export const RESET_LOGIN_STATE = "auth/RESET_LOGIN_STATE";

export const SIGNUP = 'auth/SIGNUP';
export const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'auth/SIGNUP_FAIL';

export const SEARCH_REQUEST = 'auth/SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'auth/SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAIL = 'auth/SEARCH_REQUEST_FAIL';

export const NOTIFICATION_REQUEST = 'auth/NOTIFICATION_REQUEST';
export const NOTIFICATION_REQUEST_SUCCESS = 'auth/NOTIFICATION_REQUEST_SUCCESS';
export const NOTIFICATION_REQUEST_FAIL = 'auth/NOTIFICATION_REQUEST_FAIL';

export const ACTIVE_USER_REQUEST = 'auth/ACTIVE_USER_REQUEST';
export const ACTIVE_USER_REQUEST_SUCCESS = 'auth/ACTIVE_USER_REQUEST_SUCCESS';
export const ACTIVE_USER_REQUEST_FAIL = 'auth/ACTIVE_USER_REQUEST_FAIL';





